"""Models for task input and skill output."""

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, ConfigDict, Field


class TaskSpec(BaseModel):
    """Generic task input consumed by skill implementations."""

    model_config = ConfigDict(extra="forbid")

    task_type: str
    payload: dict[str, Any] = Field(default_factory=dict)


class SkillResult(BaseModel):
    """Structured field output generated by a skill."""

    model_config = ConfigDict(extra="forbid")

    field_values: dict[str, str] = Field(default_factory=dict)
    required_fields: set[str] = Field(default_factory=set)
    optional_fields: set[str] = Field(default_factory=set)
